
 
development:
  adapter: postgresql
  encoding: unicode
  database: my_app_development
  host: localhost
  pool: 5
  username: elfgirl1981
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: my_app_test
  host: localhost
  pool: 5
  username: elfgirl1981
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: my_app_production
  host: localhost
  pool: 5
  username: elfgirl1981
  password: