# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d304e2ec3ed3229c015d07d1c5c47c85514f682b749bda0b3d20a25ff7d9c3bd30449553d98d1160d2f09574a358f3ad3579e612ba991b8133b2d950fd1ecf5f

test:
  secret_key_base: 7e3f8093c637c4b4d352cdfb9d152f464d3db338b4fe3d472a4b56e61ad21d7e14105c32312adbf1af947e88e4c7532298cee8c5805370731b801750a00fefb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
